version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Dhaka
      - TZ=Asia/Dhaka
      - N8N_AUTH_EXCLUDE_ENDPOINTS=*
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
